"""add_is_admin_column

Revision ID: f9ec4e94de91
Revises: 2a91098602cf
Create Date: 2025-01-18 19:35:41.818083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ec4e94de91'
down_revision = '2a91098602cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.drop_column('second_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_name', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
